-- Npc In Cover v6 by smallg and Necrym59
-- DESCRIPTION: Allows an NPC to pop in and out view from cover and fire at player when within range
-- DESCRIPTION: [@COVER_STYLE=1(1=Up/Down, 2=Left, 3=Right)]
-- DESCRIPTION: [ALERT_DISTANCE= 2000]
-- DESCRIPTION: [EXPOSURE_TIME=1500]
-- DESCRIPTION: [COVER_TIME=1200]
-- DESCRIPTION: [@STAND_ANIMATION=-1(0=AnimSetList)]
-- DESCRIPTION: [@DUCK_ANIMATION=-1(0=AnimSetList)]
-- DESCRIPTION: [@LEFT_ANIMATION=-1(0=AnimSetList)]
-- DESCRIPTION: [@RIGHT_ANIMATION=-1(0=AnimSetList)]
-- DESCRIPTION: [@SHOOT_ANIMATION=-1(0=AnimSetList)]
-- DESCRIPTION: [DEATH_IFUSED$=""] Object name to trigger upon death
-- DESCRIPTION: <Sound0> for entity alert 

local lower = string.lower
local npcincover 		= {}
local cover_style		= {}
local alert_distance 	= {}
local exposure_time 	= {}
local cover_time 		= {}
local stand_animation	= {}
local duck_animation	= {}
local left_animation	= {}
local right_animation	= {}
local shoot_animation	= {}
local death_ifused		= {}

local difusedno			= {}
local firerate			= {}
local firedelay 		= {}
local weaponid 			= {}
local reloadquantity	= {}
local ammo 				= {}
local standing			= {}
local status			= {}
local doonce			= {}
local playonce			= {}
local endonce			= {}

function npc_incover_properties(e, cover_style, alert_distance, exposure_time, cover_time, stand_animation, duck_animation, left_animation, right_animation, shoot_animation, death_ifused)
	npcincover[e].cover_style = cover_style
	npcincover[e].alert_distance = alert_distance
	npcincover[e].exposure_time = exposure_time
	npcincover[e].cover_time = cover_time
	npcincover[e].stand_animation = "=" .. tostring(stand_animation)
	npcincover[e].duck_animation = "=" .. tostring(duck_animation)
	npcincover[e].left_animation = "=" .. tostring(left_animation)	
	npcincover[e].right_animation = "=" .. tostring(right_animation)	
	npcincover[e].shoot_animation = "=" .. tostring(shoot_animation)
	npcincover[e].death_ifused = string.lower(death_ifused)
end

function npc_incover_init(e)
	npcincover[e] = {}
	npcincover[e].cover_style = 1
	npcincover[e].alert_distance = 2200
	npcincover[e].exposure_time = 1450
	npcincover[e].cover_time = 2000
	npcincover[e].stand_animation = ""
	npcincover[e].duck_animation = ""
	npcincover[e].left_animation = ""
	npcincover[e].right_animation = ""
	npcincover[e].shoot_animation = ""
	npcincover[e].death_ifused = ""
	
	npcincover[e].firedelay = g_Time
	npcincover[e].weaponid = GetEntityHasWeapon(e)
	npcincover[e].reloadquantity = GetWeaponReloadQuantity(npcincover[e].weaponid,0)
	npcincover[e].ammo = npcincover[e].reloadquantity
	npcincover[e].standing = e
	npcincover[e].firerate = GetWeaponFireRate(npcincover[e].weaponid,0)
	if npcincover[e].firerate >= 12 then 						-- adjust firerate to millisecond delay equiv to player
		npcincover[e].firerate = npcincover[e].firerate * 20	-- favor slower standard non-auto weapons
	else
		npcincover[e].firerate = npcincover[e].firerate * 10	-- favor faster standard automatic weapons
	end
	doonce[e] = 0
	difusedno[e] = 0
	endonce[e] = 0
	playonce[e] = 0
	math.randomseed(os.time())
	math.random(); math.random(); math.random()	
	status[e] = "init"		
end

function npc_incover_main(e)

	if status[e] == "init" then
		--Find named object with multi meshes--
		if npcincover[e].death_ifused ~= "" and difusedno[e] == 0 then
			for p = 1, g_EntityElementMax do
				if p ~= nil and g_Entity[p] ~= nil then
					difusedno[e] = p
					if string.lower(GetEntityName(p)) == npcincover[e].death_ifused then					
						difusedno[e] = p
						break
					end
				end
			end
		end	
		if npcincover[e].cover_style == 1 then
			SetAnimationName(e,npcincover[e].duck_animation)
			PlayAnimation(e)
		end	
		if npcincover[e].cover_style == 2 then
			SetAnimationName(e,npcincover[e].left_animation)
			PlayAnimation(e)
		end
		if npcincover[e].cover_style == 3 then
			SetAnimationName(e,npcincover[e].right_animation)
			PlayAnimation(e)
		end	
		SetEntityHealthSilent(e,-99999)
		status[e] = "endinit"
	end
	
	if g_Entity[e]['plrvisible'] == 0 then playonce[e] = math.random(0,5) end
	
	if (GetPlayerDistance(e)) < npcincover[e].alert_distance then 
		doonce[e] = 0				
		if npcincover[e].standing == e then
			if (GetTimer(e)) < npcincover[e].exposure_time and npcincover[e].ammo > 0 then
				RotateToPlayer(e)
				if GetEntityCanFire(e) == 1 and g_Entity[e]['plrvisible'] == 1 then
					if playonce[e] == 0 then PlaySound(e,0) end
					if g_Time > npcincover[e].firedelay then						
						FireWeaponInstant(e)
						SetAnimationName(e,npcincover[e].shoot_animation)
						PlayAnimation(e)
						npcincover[e].firedelay = g_Time + npcincover[e].firerate
						npcincover[e].ammo = npcincover[e].ammo - 1
					end
				end				
			else
				StartTimer(e)				
				npcincover[e].standing = 0
				if npcincover[e].cover_style == 1 then
					SetAnimationName(e,npcincover[e].duck_animation)
					PlayAnimation(e)
				end
				if npcincover[e].cover_style == 2 then
					SetAnimationName(e,npcincover[e].left_animation)
					PlayAnimation(e)
				end
				if npcincover[e].cover_style == 3 then
					SetAnimationName(e,npcincover[e].right_animation)
					PlayAnimation(e)
				end							
			end			
		else
			if (GetTimer(e)) < npcincover[e].cover_time then
			else
				StartTimer(e)
				if npcincover[e].standing == 0 then
					npcincover[e].standing = e
					npcincover[e].ammo = npcincover[e].reloadquantity					
					if npcincover[e].cover_style == 1 then
						SetAnimationName(e,npcincover[e].stand_animation)
						PlayAnimation(e)
					end
					if npcincover[e].cover_style == 2 then
						SetAnimationName(e,npcincover[e].stand_animation)
						PlayAnimation(e)						
					end
					if npcincover[e].cover_style == 3 then
						SetAnimationName(e,npcincover[e].stand_animation)
						PlayAnimation(e)
					end										
				end
			end
		end		
	else
		StartTimer(e)
		if npcincover[e].standing == e then 
			npcincover[e].standing = 0			
		end		
	end
	if (GetPlayerDistance(e)) > npcincover[e].alert_distance then
		if doonce[e] == 0 then
			if npcincover[e].cover_style == 1 then
				SetAnimationName(e,npcincover[e].duck_animation)
				PlayAnimation(e)
			end
			if npcincover[e].cover_style == 2 then
				SetAnimationName(e,npcincover[e].left_animation)
				PlayAnimation(e)
			end
			if npcincover[e].cover_style == 3 then
				SetAnimationName(e,npcincover[e].right_animation)
				PlayAnimation(e)
			end
			doonce[e] = 1
		end
	end	
	if g_Entity[e]['health'] <= 2 and endonce[e] == 0 then				
		SetEntityHealthSilent(e,0) -- switches off 'Prevent Zero', then uses regular health zero kill order		
		SetEntityHealth(e,1)
		if npcincover[e].death_ifused ~= "" then
			SetEntityActivated(difusedno[e],1)
			endonce[e] = 1			
		end
	end
	if endonce[e] == 1 then
		SetEntityHealth(e,0)
		SwitchScript(e,"no_behavior_selected.lua")
	end	
end

function npc_incover_exit(e)
	if npcincover[e].standing == e then
		npcincover[e].standing = 0
	end
end
