// include definition
#include <stdio.h>
#include "cerror.h"
#include "globstruct.h"
#pragma comment ( lib, "user32.lib" )
#define DB_PRO 1

// Handler Passed into DLL
CRuntimeErrorHandler* g_pErrorHandler = NULL;

// Externals
extern bool g_bCascadeQuitFlag;
extern char g_strErrorClue[512];
int g_iIgnoreAllErrors = 0;

#ifndef NOSTEAMORVIDEO
void timestampactivity(int i, char* desc_s);
#endif

// access to LUA extra debug info
#include ".\..\..\..\..\Guru-WickedMAX\CrashLogger.h"
#include ".\..\..\..\..\Guru-WickedMAX\wickedcalls.h"
extern "C" {
#include ".\..\Dark Basic Pro SDK\DarkSDKMore\DarkLUA\lua\lstate.h" 
}
extern thread_local lua_State* g_CurrentLuaState;

void Error1 ( char* szMessage )
{
	if(g_pErrorHandler)
		if(g_pErrorHandler->dwErrorCode==0)
			RunTimeError(RUNTIMEERROR_GENERICERROR, szMessage);
}

void Message ( int iID, char* szMessage, char* szTitle )
{
	MessageBox ( NULL, szMessage, szTitle, MB_OK | MB_ICONINFORMATION | MB_SYSTEMMODAL | MB_TOPMOST );
}

#include <string>

void GetRuntimeErrorDescription(int errorCode, std::string* outString)
{
    if (!outString) return;

    switch (errorCode)
    {
		case RUNTIMEERROR_GENERICERROR: *outString = "GENERICERROR"; break;
		case RUNTIMEERROR_TRIEDTORUNFUNCTIONHEADER: *outString = "TRIEDTORUNFUNCTIONHEADER"; break;
		case RUNTIMEERROR_ARRAYACCESSEDOUTOFBOUNDS: *outString = "ARRAYACCESSEDOUTOFBOUNDS"; break;
		case RUNTIMEERROR_ARRAYINDEXINVALID: *outString = "ARRAYINDEXINVALID"; break;
		case RUNTIMEERROR_ARRAYEMPTY: *outString = "ARRAYEMPTY"; break;
		case RUNTIMEERROR_ARRAYTYPEINVALID: *outString = "ARRAYTYPEINVALID"; break;
		case RUNTIMEERROR_ARRAYMUSTBESINGLEDIM: *outString = "ARRAYMUSTBESINGLEDIM"; break;

		case RUNTIMEERROR_NOTENOUGHMEMORY: *outString = "NOTENOUGHMEMORY"; break;
		case RUNTIMEERROR_INVALIDARRAYUSE: *outString = "INVALIDARRAYUSE"; break;
		case RUNTIMEERROR_FILETOOLARGE: *outString = "FILETOOLARGE"; break;
		case RUNTIMEERROR_INVALIDFILE: *outString = "INVALIDFILE"; break;
		case RUNTIMEERROR_FILENOTEXIST: *outString = "FILENOTEXIST"; break;
		case RUNTIMEERROR_FILEEXISTS: *outString = "FILEEXISTS"; break;
		case RUNTIMEERROR_STRINGLENGTHOVERFLOW: *outString = "STRINGLENGTHOVERFLOW"; break;
		case RUNTIMEERROR_STACKOVERFLOW: *outString = "STACKOVERFLOW"; break;
		case RUNTIMEERROR_INVALIDARRAY: *outString = "INVALIDARRAY"; break;
		case RUNTIMEERROR_MUSTBEPOSITIVEVALUE: *outString = "MUSTBEPOSITIVEVALUE"; break;
		case RUNTIMEERROR_DIVIDEBYZERO: *outString = "DIVIDEBYZERO"; break;
		case RUNTIMEERROR_SYNCRATEINVALID: *outString = "SYNCRATEINVALID"; break;
		case RUNTIMEERROR_RANDOMVALUEPOSITIVE: *outString = "RANDOMVALUEPOSITIVE"; break;
		case RUNTIMEERROR_CANONLYINCREMENTVARIABLE: *outString = "CANONLYINCREMENTVARIABLE"; break;
		case RUNTIMEERROR_CANONLYDECREMENTVARIABLE: *outString = "CANONLYDECREMENTVARIABLE"; break;
		case RUNTIMEERROR_COMMANDNOWOBSOLETE: *outString = "COMMANDNOWOBSOLETE"; break;
		case RUNTIMEERROR_FILEISLOCKED: *outString = "FILEISLOCKED"; break;

		case RUNTIMEERROR_SPRITEERROR: *outString = "SPRITEERROR"; break;
		case RUNTIMEERROR_SPRITEILLEGALNUMBER: *outString = "SPRITEILLEGALNUMBER"; break;
		case RUNTIMEERROR_SPRITENOTEXIST: *outString = "SPRITENOTEXIST"; break;
		case RUNTIMEERROR_SPRITEBACKSAVEILLEGAL: *outString = "SPRITEBACKSAVEILLEGAL"; break;
		case RUNTIMEERROR_SPRITETRANSPARENCYILLEGAL: *outString = "SPRITETRANSPARENCYILLEGAL"; break;
		case RUNTIMEERROR_SPRITEROTATIONILLEGAL: *outString = "SPRITEROTATIONILLEGAL"; break;
		case RUNTIMEERROR_SPRITESCALEILLEGAL: *outString = "SPRITESCALEILLEGAL"; break;
		case RUNTIMEERROR_SPRITESIZEILLEGAL: *outString = "SPRITESIZEILLEGAL"; break;
		case RUNTIMEERROR_SPRITEANGLEILLEGAL: *outString = "SPRITEANGLEILLEGAL"; break;
		case RUNTIMEERROR_SPRITEALPHAVALUEILLEGAL: *outString = "SPRITEALPHAVALUEILLEGAL"; break;
		case RUNTIMEERROR_SPRITERGBCOMPONENTILLEGAL: *outString = "SPRITERGBCOMPONENTILLEGAL"; break;
		case RUNTIMEERROR_SPRITEANIMDELAYILLEGAL: *outString = "SPRITEANIMDELAYILLEGAL"; break;
		case RUNTIMEERROR_SPRITEVERTEXILLEGAL: *outString = "SPRITEVERTEXILLEGAL"; break;
		case RUNTIMEERROR_SPRITEWIDTHILLEGAL: *outString = "SPRITEWIDTHILLEGAL"; break;
		case RUNTIMEERROR_SPRITEHEIGHTILLEGAL: *outString = "SPRITEHEIGHTILLEGAL"; break;
		case RUNTIMEERROR_SPRITEHANIMCOUNTILLEGAL: *outString = "SPRITEHANIMCOUNTILLEGAL"; break;
		case RUNTIMEERROR_SPRITEALREADYTEXISTS: *outString = "SPRITEALREADYTEXISTS"; break;

		case RUNTIMEERROR_IMAGEERROR: *outString = "IMAGEERROR"; break;
		case RUNTIMEERROR_IMAGEILLEGALNUMBER: *outString = "IMAGEILLEGALNUMBER"; break;
		case RUNTIMEERROR_IMAGENOTEXIST: *outString = "IMAGENOTEXIST"; break;
		case RUNTIMEERROR_IMAGEGRABTOOLARGE: *outString = "IMAGEGRABTOOLARGE"; break;
		case RUNTIMEERROR_IMAGEAREAILLEGAL: *outString = "IMAGEAREAILLEGAL"; break;
		case RUNTIMEERROR_IMAGETOOBIGASTEXTURE: *outString = "IMAGETOOBIGASTEXTURE"; break;
		case RUNTIMEERROR_IMAGELOADFAILED: *outString = "IMAGELOADFAILED"; break;
		case RUNTIMEERROR_IMAGELOCKED: *outString = "IMAGELOCKED"; break;

		case RUNTIMEERROR_BITMAPERROR: *outString = "BITMAPERROR"; break;
		case RUNTIMEERROR_BITMAPILLEGALNUMBER: *outString = "BITMAPILLEGALNUMBER"; break;
		case RUNTIMEERROR_BITMAPNOTEXIST: *outString = "BITMAPNOTEXIST"; break;
		case RUNTIMEERROR_BITMAPLOADFAILED: *outString = "BITMAPLOADFAILED"; break;
		case RUNTIMEERROR_BITMAPSAVEFAILED: *outString = "BITMAPSAVEFAILED"; break;
		case RUNTIMEERROR_BITMAPCREATEFAILED: *outString = "BITMAPCREATEFAILED"; break;
		case RUNTIMEERROR_BITMAPZERONODELETE: *outString = "BITMAPZERONODELETE"; break;
		case RUNTIMEERROR_BITMAPBOTHSAME: *outString = "BITMAPBOTHSAME"; break;
		case RUNTIMEERROR_BITMAPSOURCETOOLARGE: *outString = "BITMAPSOURCETOOLARGE"; break;
		case RUNTIMEERROR_BITMAPZERORESERVED: *outString = "BITMAPZERORESERVED"; break;
		case RUNTIMEERROR_BITMAPREGIONEXCEEDED: *outString = "BITMAPREGIONEXCEEDED"; break;
		case RUNTIMEERROR_BITMAPAREASINVALID: *outString = "BITMAPAREASINVALID"; break;
		case RUNTIMEERROR_BITMAPBLURVALUEILLEGAL: *outString = "BITMAPBLURVALUEILLEGAL"; break;
		case RUNTIMEERROR_BITMAPFADEVALUEILLEGAL: *outString = "BITMAPFADEVALUEILLEGAL"; break;
		case RUNTIMEERROR_BITMAPGAMMAILLEGAL: *outString = "BITMAPGAMMAILLEGAL"; break;

		case RUNTIMEERROR_SCREEN: *outString = "SCREEN"; break;
		case RUNTIMEERROR_SCREENSIZEILLEGAL: *outString = "SCREENSIZEILLEGAL"; break;
		case RUNTIMEERROR_SCREENDEPTHILLEGAL: *outString = "SCREENDEPTHILLEGAL"; break;
		case RUNTIMEERROR_SCREENMODEINVALID: *outString = "SCREENMODEINVALID"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAY: *outString = "NOTSUPPORTDISPLAY"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAY16B: *outString = "NOTSUPPORTDISPLAY16B"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAY24B: *outString = "NOTSUPPORTDISPLAY24B"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAY32B: *outString = "NOTSUPPORTDISPLAY32B"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYVB: *outString = "NOTSUPPORTDISPLAYVB"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYLOCK: *outString = "NOTSUPPORTDISPLAYLOCK"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYNODX: *outString = "NOTSUPPORTDISPLAYNODX"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYINVALID: *outString = "NOTSUPPORTDISPLAYINVALID"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYNOTAVAIL: *outString = "NOTSUPPORTDISPLAYNOTAVAIL"; break;
		case RUNTIMEERROR_NOTSUPPORTDISPLAYNOVID: *outString = "NOTSUPPORTDISPLAYNOVID"; break;
		case RUNTIMEERROR_24BITNOTSUPPORTED: *outString = "24BITNOTSUPPORTED"; break;

		case RUNTIMEERROR_ANIMERROR: *outString = "ANIMERROR"; break;
		case RUNTIMEERROR_ANIMNUMBERILLEGAL: *outString = "ANIMNUMBERILLEGAL"; break;
		case RUNTIMEERROR_ANIMLOADFAILED: *outString = "ANIMLOADFAILED"; break;
		case RUNTIMEERROR_ANIMALREADYEXISTS: *outString = "ANIMALREADYEXISTS"; break;
		case RUNTIMEERROR_ANIMNOTEXIST: *outString = "ANIMNOTEXIST"; break;
		case RUNTIMEERROR_ANIMVOLUMEILLEGAL: *outString = "ANIMVOLUMEILLEGAL"; break;
		case RUNTIMEERROR_ANIMFREQILLEGAL: *outString = "ANIMFREQILLEGAL"; break;
		case RUNTIMEERROR_ANIMALREADYPLAYING: *outString = "ANIMALREADYPLAYING"; break;
		case RUNTIMEERROR_ANIMNOTPLAYING: *outString = "ANIMNOTPLAYING"; break;
		case RUNTIMEERROR_ANIMALREADYPAUSED: *outString = "ANIMALREADYPAUSED"; break;
		case RUNTIMEERROR_ANIMNOTPAUSED: *outString = "ANIMNOTPAUSED"; break;

		case RUNTIMEERROR_SOUNDERROR: *outString = "SOUNDERROR"; break;
		case RUNTIMEERROR_SOUNDNUMBERILLEGAL: *outString = "SOUNDNUMBERILLEGAL"; break;
		case RUNTIMEERROR_SOUNDLOADFAILED: *outString = "SOUNDLOADFAILED"; break;
		case RUNTIMEERROR_SOUNDALREADYEXISTS: *outString = "SOUNDALREADYEXISTS"; break;
		case RUNTIMEERROR_SOUNDNOTEXIST: *outString = "SOUNDNOTEXIST"; break;
		case RUNTIMEERROR_SOUNDVOLUMEILLEGAL: *outString = "SOUNDVOLUMEILLEGAL"; break;
		case RUNTIMEERROR_SOUNDFREQILLEGAL: *outString = "SOUNDFREQILLEGAL"; break;
		case RUNTIMEERROR_SOUNDPANVALUEILLEGAL: *outString = "SOUNDPANVALUEILLEGAL"; break;
		case RUNTIMEERROR_SOUNDSAVEFAILED: *outString = "SOUNDSAVEFAILED"; break;
		case RUNTIMEERROR_SOUNDCANNOTBECLONED: *outString = "SOUNDCANNOTBECLONED"; break;
		case RUNTIMEERROR_SOUNDMUSTSPECIFYSOUND: *outString = "SOUNDMUSTSPECIFYSOUND"; break;
		case RUNTIMEERROR_SOUNDMUSTSPECIFYCLONE: *outString = "SOUNDMUSTSPECIFYCLONE"; break;

		case RUNTIMEERROR_NOSPEECHENGINE: *outString = "NOSPEECHENGINE"; break;

		case RUNTIMEERROR_MUSICERROR: *outString = "MUSICERROR"; break;
		case RUNTIMEERROR_MUSICNUMBERILLEGAL: *outString = "MUSICNUMBERILLEGAL"; break;
		case RUNTIMEERROR_MUSICLOADFAILED: *outString = "MUSICLOADFAILED"; break;
		case RUNTIMEERROR_MUSICALREADYEXISTS: *outString = "MUSICALREADYEXISTS"; break;
		case RUNTIMEERROR_MUSICNOTEXIST: *outString = "MUSICNOTEXIST"; break;
		case RUNTIMEERROR_MUSICVOLUMEILLEGAL: *outString = "MUSICVOLUMEILLEGAL"; break;
		case RUNTIMEERROR_MUSICSPEEDILLEGAL: *outString = "MUSICSPEEDILLEGAL"; break;
		case RUNTIMEERROR_MUSICNOTPLAYING: *outString = "MUSICNOTPLAYING"; break;
		case RUNTIMEERROR_MUSICTRACKILLEGAL: *outString = "MUSICTRACKILLEGAL"; break;

		case RUNTIMEERROR_INPUTCONTROLLERNOTAVAIL: *outString = "INPUTCONTROLLERNOTAVAIL"; break;
		case RUNTIMEERROR_INPUTNOCONTROLLERSELECTED: *outString = "INPUTNOCONTROLLERSELECTED"; break;
		case RUNTIMEERROR_INPUTFORCEFEEDBACKNOTAVAIL: *outString = "INPUTFORCEFEEDBACKNOTAVAIL"; break;
		case RUNTIMEERROR_INPUTFFMAGNITUDEERROR: *outString = "INPUTFFMAGNITUDEERROR"; break;
		case RUNTIMEERROR_INPUTFFDURATIONERROR: *outString = "INPUTFFDURATIONERROR"; break;
		case RUNTIMEERROR_INPUTFFANGLEERROR: *outString = "INPUTFFANGLEERROR"; break;

		case RUNTIMEERROR_MEMBLOCKRANGEILLEGAL: *outString = "MEMBLOCKRANGEILLEGAL"; break;
		case RUNTIMEERROR_MEMBLOCKALREADYEXISTS: *outString = "MEMBLOCKALREADYEXISTS"; break;
		case RUNTIMEERROR_MEMBLOCKNOTEXIST: *outString = "MEMBLOCKNOTEXIST"; break;
		case RUNTIMEERROR_MEMBLOCKCREATIONFAILED: *outString = "MEMBLOCKCREATIONFAILED"; break;
		case RUNTIMEERROR_MEMBLOCKOUTSIDERANGE: *outString = "MEMBLOCKOUTSIDERANGE"; break;
		case RUNTIMEERROR_MEMBLOCKSIZEINVALID: *outString = "MEMBLOCKSIZEINVALID"; break;
		case RUNTIMEERROR_MEMBLOCKNOTABYTE: *outString = "MEMBLOCKNOTABYTE"; break;
		case RUNTIMEERROR_MEMBLOCKNOTAWORD: *outString = "MEMBLOCKNOTAWORD"; break;
		case RUNTIMEERROR_MEMBLOCKNOTADWORD: *outString = "MEMBLOCKNOTADWORD"; break;

		case RUNTIMEERROR_B3DERROR: *outString = "B3DERROR"; break;
		case RUNTIMEERROR_B3DMESHNUMBERILLEGAL: *outString = "B3DMESHNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DMESHLOADFAILED: *outString = "B3DMESHLOADFAILED"; break;
		case RUNTIMEERROR_B3DMESHNOTEXIST: *outString = "B3DMESHNOTEXIST"; break;
		case RUNTIMEERROR_B3DMESHDARKENILLEGAL: *outString = "B3DMESHDARKENILLEGAL"; break;
		case RUNTIMEERROR_B3DMESHLIGHTENILLEGAL: *outString = "B3DMESHLIGHTENILLEGAL"; break;
		case RUNTIMEERROR_B3DMODELNUMBERILLEGAL: *outString = "B3DMODELNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DMODELALREADYEXISTS: *outString = "B3DMODELALREADYEXISTS"; break;
		case RUNTIMEERROR_B3DMODELNOTEXISTS: *outString = "B3DMODELNOTEXISTS"; break;
		case RUNTIMEERROR_B3DMATRIXALREADYEXISTS: *outString = "B3DMATRIXALREADYEXISTS"; break;
		case RUNTIMEERROR_B3DMATRIXNUMBERILLEGAL: *outString = "B3DMATRIXNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DMATRIXDIMENSIONWRONG: *outString = "B3DMATRIXDIMENSIONWRONG"; break;
		case RUNTIMEERROR_B3DMATRIXSEGMENTWRONG: *outString = "B3DMATRIXSEGMENTWRONG"; break;
		case RUNTIMEERROR_B3DMATRIXNOTEXISTS: *outString = "B3DMATRIXNOTEXISTS"; break;
		case RUNTIMEERROR_B3DMATRIXNOHEIGHTMAX: *outString = "B3DMATRIXNOHEIGHTMAX"; break;
		case RUNTIMEERROR_B3DMATRIXTOOLARGE: *outString = "B3DMATRIXTOOLARGE"; break;
		case RUNTIMEERROR_B3DMATRIXTILEILLEGAL: *outString = "B3DMATRIXTILEILLEGAL"; break;
		case RUNTIMEERROR_B3DMATRIXTILECOORDSWRONG: *outString = "B3DMATRIXTILECOORDSWRONG"; break;
		case RUNTIMEERROR_B3DOBJECTLOADFAILED: *outString = "B3DOBJECTLOADFAILED"; break;
		case RUNTIMEERROR_B3DANGLERANGEERROR: *outString = "B3DANGLERANGEERROR"; break;
		case RUNTIMEERROR_B3DOBJECTTOOMANYLIMBS: *outString = "B3DOBJECTTOOMANYLIMBS"; break;
		case RUNTIMEERROR_B3DMEMORYERROR: *outString = "B3DMEMORYERROR"; break;
		case RUNTIMEERROR_B3DMUSTUSEDBOEXTENSION: *outString = "B3DMUSTUSEDBOEXTENSION"; break;

		case RUNTIMEERROR_CAMERANUMBERILLEGAL: *outString = "CAMERANUMBERILLEGAL"; break;
		case RUNTIMEERROR_CAMERAALREADYEXISTS: *outString = "CAMERAALREADYEXISTS"; break;
		case RUNTIMEERROR_CAMERANOTEXIST: *outString = "CAMERANOTEXIST"; break;
		case RUNTIMEERROR_CAMERACANNOTCREATE: *outString = "CAMERACANNOTCREATE"; break;
		case RUNTIMEERROR_CAMERANOZERO: *outString = "CAMERANOZERO"; break;

		case RUNTIMEERROR_B3DLIGHTNUMBERILLEGAL: *outString = "B3DLIGHTNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DLIGHTALREADYEXISTS: *outString = "B3DLIGHTALREADYEXISTS"; break;
		case RUNTIMEERROR_B3DLIGHTNOTEXIST: *outString = "B3DLIGHTNOTEXIST"; break;
		case RUNTIMEERROR_B3DLIGHTCANNOTCREATE: *outString = "B3DLIGHTCANNOTCREATE"; break;
		case RUNTIMEERROR_B3DLIGHTNOZERO: *outString = "B3DLIGHTNOZERO"; break;

		case RUNTIMEERROR_LIMBNUMBERILLEGAL: *outString = "LIMBNUMBERILLEGAL"; break;
		case RUNTIMEERROR_LIMBADDNUMBERILLEGAL: *outString = "LIMBADDNUMBERILLEGAL"; break;
		case RUNTIMEERROR_LIMBNOTEXIST: *outString = "LIMBNOTEXIST"; break;
		case RUNTIMEERROR_LIMBALREADYEXISTS: *outString = "LIMBALREADYEXISTS"; break;
		case RUNTIMEERROR_LINKNOTPOSSIBLE: *outString = "LINKNOTPOSSIBLE"; break;
		case RUNTIMEERROR_LIMBMUSTCHAININSEQUENCE: *outString = "LIMBMUSTCHAININSEQUENCE"; break;
		case RUNTIMEERROR_LINKSHOULDBENEW: *outString = "LINKSHOULDBENEW"; break;
		case RUNTIMEERROR_B3DMESHTOOLARGE: *outString = "B3DMESHTOOLARGE"; break;

		case RUNTIMEERROR_B3DMODELFADEINVALID: *outString = "B3DMODELFADEINVALID"; break;
		case RUNTIMEERROR_B3DLIMBBUTNOMESH: *outString = "B3DLIMBBUTNOMESH"; break;

		case RUNTIMEERROR_PARTICLESALREADYEXISTS: *outString = "PARTICLESALREADYEXISTS"; break;
		case RUNTIMEERROR_PARTICLESNOTEXIST: *outString = "PARTICLESNOTEXIST"; break;
		case RUNTIMEERROR_PARTICLESERROR: *outString = "PARTICLESERROR"; break;
		case RUNTIMEERROR_PARTICLESNUMBERILLEGAL: *outString = "PARTICLESNUMBERILLEGAL"; break;
		case RUNTIMEERROR_PARTICLESCOULDNOTBECREATED: *outString = "PARTICLESCOULDNOTBECREATED"; break;

		case RUNTIMEERROR_TERRAINFAILEDCREATE: *outString = "TERRAINFAILEDCREATE"; break;
		case RUNTIMEERROR_TERRAINALREADYEXIST: *outString = "TERRAINALREADYEXIST"; break;
		case RUNTIMEERROR_TERRAINNOTEXIST: *outString = "TERRAINNOTEXIST"; break;
		case RUNTIMEERROR_TERRAINFILEMUSTBESQUARE: *outString = "TERRAINFILEMUSTBESQUARE"; break;
		case RUNTIMEERROR_TERRAINNUMBERILLEGAL: *outString = "TERRAINNUMBERILLEGAL"; break;

		case RUNTIMEERROR_BSPLOADFAILED: *outString = "BSPLOADFAILED"; break;
		case RUNTIMEERROR_BSPNOTEXIST: *outString = "BSPNOTEXIST"; break;
		case RUNTIMEERROR_BSPALREADYEXIST: *outString = "BSPALREADYEXIST"; break;
		case RUNTIMEERROR_BSPCOLLISIONNUMBERILLEGAL: *outString = "BSPCOLLISIONNUMBERILLEGAL"; break;

		case RUNTIMEERROR_B3DMODELDOESNOTANIMATE: *outString = "B3DMODELDOESNOTANIMATE"; break;
		case RUNTIMEERROR_B3DKEYFRAMENOTEXIST: *outString = "B3DKEYFRAMENOTEXIST"; break;
		case RUNTIMEERROR_B3DANIMSPEEDERROR: *outString = "B3DANIMSPEEDERROR"; break;
		case RUNTIMEERROR_B3DANIMINTERPERROR: *outString = "B3DANIMINTERPERROR"; break;
		case RUNTIMEERROR_B3DOBJECTAPPENDFAILED: *outString = "B3DOBJECTAPPENDFAILED"; break;
		case RUNTIMEERROR_B3DOBJECTAPPENDTOOLOW: *outString = "B3DOBJECTAPPENDTOOLOW"; break;
		case RUNTIMEERROR_FAILEDTOCOMPILECSG: *outString = "FAILEDTOCOMPILECSG"; break;

		case RUNTIMEERROR_B3DVSHADERNUMBERILLEGAL: *outString = "B3DVSHADERNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DVSHADERCOUNTILLEGAL: *outString = "B3DVSHADERCOUNTILLEGAL"; break;
		case RUNTIMEERROR_B3DVSHADERCANNOTCREATE: *outString = "B3DVSHADERCANNOTCREATE"; break;
		case RUNTIMEERROR_B3DVSHADERSTREAMPOSINVALID: *outString = "B3DVSHADERSTREAMPOSINVALID"; break;
		case RUNTIMEERROR_B3DVSHADERDATAINVALID: *outString = "B3DVSHADERDATAINVALID"; break;
		case RUNTIMEERROR_B3DVSHADERINVALIDSTREAM: *outString = "B3DVSHADERINVALIDSTREAM"; break;
		case RUNTIMEERROR_B3DVSHADERCANNOTASSEMBLE: *outString = "B3DVSHADERCANNOTASSEMBLE"; break;
		case RUNTIMEERROR_B3DVSHADERINVALID: *outString = "B3DVSHADERINVALID"; break;

		case RUNTIMEERROR_B3DEFFECTNUMBERILLEGAL: *outString = "B3DEFFECTNUMBERILLEGAL"; break;
		case RUNTIMEERROR_B3DEFFECTNOTEXISTS: *outString = "B3DEFFECTNOTEXISTS"; break;
		case RUNTIMEERROR_B3DEFFECTALREADYEXISTS: *outString = "B3DEFFECTALREADYEXISTS"; break;

		case RUNTIMEERROR_VECTORNOTEXIST: *outString = "VECTORNOTEXIST"; break;
		case RUNTIMEERROR_MATRIX4NOTEXIST: *outString = "MATRIX4NOTEXIST"; break;
		case RUNTIMEERROR_VECTORNUMBERILLEGAL: *outString = "VECTORNUMBERILLEGAL"; break;
		case RUNTIMEERROR_MATRIX4NUMBERILLEGAL: *outString = "MATRIX4NUMBERILLEGAL"; break;

		case RUNTIMEERROR_B3DFOGNOTABLE: *outString = "B3DFOGNOTABLE"; break;
		case RUNTIMEERROR_B3DAMBIENTPERCENTAGEERROR: *outString = "B3DAMBIENTPERCENTAGEERROR"; break;
		case RUNTIMEERROR_B3DCAMERARANGEERROR: *outString = "B3DCAMERARANGEERROR"; break;

		case RUNTIMEERROR_B3DSOURCEMUSTBE3DS: *outString = "B3DSOURCEMUSTBE3DS"; break;
		case RUNTIMEERROR_B3DDESTMUSTBEX: *outString = "B3DDESTMUSTBEX"; break;

		case RUNTIMEERROR_CANNOTSCANCURRENTDIR: *outString = "CANNOTSCANCURRENTDIR"; break;
		case RUNTIMEERROR_NOMOREFILESINDIR: *outString = "NOMOREFILESINDIR"; break;
		case RUNTIMEERROR_PATHCANNOTBEFOUND: *outString = "PATHCANNOTBEFOUND"; break;
		case RUNTIMEERROR_CANNOTMAKEFILE: *outString = "CANNOTMAKEFILE"; break;
		case RUNTIMEERROR_CANNOTDELETEFILE: *outString = "CANNOTDELETEFILE"; break;
		case RUNTIMEERROR_CANNOTCOPYFILE: *outString = "CANNOTCOPYFILE"; break;
		case RUNTIMEERROR_CANNOTRENAMEFILE: *outString = "CANNOTRENAMEFILE"; break;
		case RUNTIMEERROR_CANNOTMOVEFILE: *outString = "CANNOTMOVEFILE"; break;
		case RUNTIMEERROR_CANNOTMAKEDIR: *outString = "CANNOTMAKEDIR"; break;
		case RUNTIMEERROR_CANNOTDELETEDIR: *outString = "CANNOTDELETEDIR"; break;
		case RUNTIMEERROR_CANNOTEXECUTEFILE: *outString = "CANNOTEXECUTEFILE"; break;

		case RUNTIMEERROR_CANNOTOPENFILEFORREADING: *outString = "CANNOTOPENFILEFORREADING"; break;
		case RUNTIMEERROR_CANNOTOPENFILEFORWRITING: *outString = "CANNOTOPENFILEFORWRITING"; break;
		case RUNTIMEERROR_FILEALREADYOPEN: *outString = "FILEALREADYOPEN"; break;
		case RUNTIMEERROR_FILENOTOPEN: *outString = "FILENOTOPEN"; break;
		case RUNTIMEERROR_CANNOTREADFROMFILE: *outString = "CANNOTREADFROMFILE"; break;
		case RUNTIMEERROR_CANNOTWRITETOFILE: *outString = "CANNOTWRITETOFILE"; break;
		case RUNTIMEERROR_FILENUMBERINVALID: *outString = "FILENUMBERINVALID"; break;

		case RUNTIMEERROR_FTPCONNECTIONFAILED: *outString = "FTPCONNECTIONFAILED"; break;
		case RUNTIMEERROR_FTPPATHCANNOTBEFOUND: *outString = "FTPPATHCANNOTBEFOUND"; break;
		case RUNTIMEERROR_FTPCANNOTPUTFILE: *outString = "FTPCANNOTPUTFILE"; break;
		case RUNTIMEERROR_FTPCANNOTDELETEFILE: *outString = "FTPCANNOTDELETEFILE"; break;
		case RUNTIMEERROR_FTPCANNOTGETFILE: *outString = "FTPCANNOTGETFILE"; break;

		case RUNTIMEERROR_MPFAILEDTOCONNECT: *outString = "MPFAILEDTOCONNECT"; break;
		case RUNTIMEERROR_MPFAILEDTOFINDSESSION: *outString = "MPFAILEDTOFINDSESSION"; break;
		case RUNTIMEERROR_MPFAILEDTOSETSESSION: *outString = "MPFAILEDTOSETSESSION"; break;
		case RUNTIMEERROR_MPFAILEDTOCREATEGAME: *outString = "MPFAILEDTOCREATEGAME"; break;
		case RUNTIMEERROR_MPFAILEDTOJOINGAME: *outString = "MPFAILEDTOJOINGAME"; break;
		case RUNTIMEERROR_MPFAILEDTOSENDMESSAGE: *outString = "MPFAILEDTOSENDMESSAGE"; break;

		case RUNTIMEERROR_MPCREATEBETWEEN2AND255: *outString = "MPCREATEBETWEEN2AND255"; break;
		case RUNTIMEERROR_MPMUSTGIVEPLAYERNAME: *outString = "MPMUSTGIVEPLAYERNAME"; break;
		case RUNTIMEERROR_MPMUSTGIVEGAMENAME: *outString = "MPMUSTGIVEGAMENAME"; break;
		case RUNTIMEERROR_MPCONNECTIONNUMINVALID: *outString = "MPCONNECTIONNUMINVALID"; break;
		case RUNTIMEERROR_MPSESSIONNUMINVALID: *outString = "MPSESSIONNUMINVALID"; break;
		case RUNTIMEERROR_MPPLAYERNUMINVALID: *outString = "MPPLAYERNUMINVALID"; break;
		case RUNTIMEERROR_MPNOTINSESSION: *outString = "MPNOTINSESSION"; break;
		case RUNTIMEERROR_MPPLAYERNOTEXIST: *outString = "MPPLAYERNOTEXIST"; break;
		case RUNTIMEERROR_MPSESSIONEXISTS: *outString = "MPSESSIONEXISTS"; break;
		case RUNTIMEERROR_MPNOTCREATEDPLAYER: *outString = "MPNOTCREATEDPLAYER"; break;
		case RUNTIMEERROR_MPCANNOTDELETEPLAYER: *outString = "MPCANNOTDELETEPLAYER"; break;
		case RUNTIMEERROR_MPTOOMANYPLAYERS: *outString = "MPTOOMANYPLAYERS"; break;

		case RUNTIMEERROR_CHECKLISTILLEGALNUMBER: *outString = "CHECKLISTILLEGALNUMBER"; break;
		case RUNTIMEERROR_CHECKLISTNUMBERWRONG: *outString = "CHECKLISTNUMBERWRONG"; break;
		case RUNTIMEERROR_CHECKLISTONLYVALUES: *outString = "CHECKLISTONLYVALUES"; break;
		case RUNTIMEERROR_CHECKLISTONLYSTRINGS: *outString = "CHECKLISTONLYSTRINGS"; break;
		case RUNTIMEERROR_CHECKLISTNOTEXIST: *outString = "CHECKLISTNOTEXIST"; break;
		case RUNTIMEERROR_SYSCARDNOTFOUND: *outString = "SYSCARDNOTFOUND"; break;
		case RUNTIMEERROR_SYSCOULDNOTGETTEXMEM: *outString = "SYSCOULDNOTGETTEXMEM"; break;
		case RUNTIMEERROR_SYSCOULDNOTGETVIDMEM: *outString = "SYSCOULDNOTGETVIDMEM"; break;
		case RUNTIMEERROR_SYSCOULDNOTGETSYSMEM: *outString = "SYSCOULDNOTGETSYSMEM"; break;

		case RUNTIMEERROR_SYSCOULDNOTLOADDLL: *outString = "SYSCOULDNOTLOADDLL"; break;
		case RUNTIMEERROR_SYSDLLNOTEXIST: *outString = "SYSDLLNOTEXIST"; break;
		case RUNTIMEERROR_SYSDLLALREADYEXISTS: *outString = "SYSDLLALREADYEXISTS"; break;
		case RUNTIMEERROR_SYSDLLCALLFAILED: *outString = "SYSDLLCALLFAILED"; break;
		case RUNTIMEERROR_SYSDLLINDEXINVALID: *outString = "SYSDLLINDEXINVALID"; break;

		case RUNTIMEERROR_OBJECTMANAGERFAILED: *outString = "OBJECTMANAGERFAILED"; break;

        default:
            *outString = "UNKNOWN_ERROR";
            break;
    }
}

void RunTimeError ( DWORD dwErrorCode )
{
	//C++Conversion
	char szErrorString[1024];
    std::string err = "";
    GetRuntimeErrorDescription(dwErrorCode, &err);
	if(strlen(g_strErrorClue)>0)
		sprintf ( szErrorString , "Runtime Error %i: %s (%s)" , dwErrorCode, err.c_str(), g_strErrorClue );
	else
		sprintf ( szErrorString , "Runtime Error %i: %s", dwErrorCode, err.c_str());

	// add LUA trace if any
	if (g_CurrentLuaState)
	{
		lua_Debug ar;
		if (lua_getstack(g_CurrentLuaState, 1, &ar))
		{
			lua_getinfo(g_CurrentLuaState, "Sl", &ar);
			char pLUAErr[1024];
			sprintf(pLUAErr, ". Found in '%s' at line %d.", ar.short_src, ar.currentline);
			strcat(szErrorString, pLUAErr);
		}
		g_CurrentLuaState = nullptr;
	}

	// Ensure any runtime error is added to crash log content
	GG_CRASH_CONTEXT("RunTimeError", "%s", szErrorString);

	#ifndef NOSTEAMORVIDEO
	timestampactivity(0, szErrorString);
	#endif
	if (g_iIgnoreAllErrors == 0)
	{
		MessageBox(NULL, szErrorString, "Error", MB_OK | MB_TOPMOST);
		CrashHandler(NULL);
		//Debug trick , trigger Visual Studio breakpoint. Then use F10 to go to the place the error was generated. also comment out ExitProcess ( 0 );
		__debugbreak();
		ExitProcess(0);
	}
}

void RunTimeWarning ( DWORD dwErrorCode )
{
}

void RunTimeSoftWarning ( DWORD dwErrorCode )
{
}

void RunTimeError(DWORD dwErrorCode, LPSTR pExtraErrorString)
{
	if ( pExtraErrorString ) 
	{
		char szErrorString[MAX_PATH];
        std::string err = "";
        GetRuntimeErrorDescription(dwErrorCode, &err);
		if (strlen(g_strErrorClue) > 0)
			sprintf(szErrorString, "Runtime Error %i: %s %s (%s)" , dwErrorCode, err.c_str(), pExtraErrorString, g_strErrorClue );
		else
			sprintf(szErrorString, "Runtime Error %i: %s %s", dwErrorCode, err.c_str(), pExtraErrorString);

		// add LUA trace if any
		if (g_CurrentLuaState)
		{
			lua_Debug ar;
			if (lua_getstack(g_CurrentLuaState, 1, &ar))
			{
				lua_getinfo(g_CurrentLuaState, "Sl", &ar);
				char pLUAErr[1024];
				sprintf(pLUAErr, ". Found in '%s' at line %d.", ar.short_src, ar.currentline);
				strcat(szErrorString, pLUAErr);
			}
			g_CurrentLuaState = nullptr;
		}

		// Ensure any runtime error is added to crash log content
		GG_CRASH_CONTEXT("RunTimeError", "%s", szErrorString);

		#ifndef NOSTEAMORVIDEO
		timestampactivity(0, szErrorString);
		#endif
		if (g_iIgnoreAllErrors == 0)
		{
			MessageBox(NULL, szErrorString, "Error", MB_OK | MB_TOPMOST);
			CrashHandler(NULL);
			__debugbreak();
			ExitProcess(0);
		}
	}
	else
	{
		RunTimeError ( dwErrorCode );
	}
}

void LastSystemError()
{
	LPVOID lpBuffer;
	if (g_iIgnoreAllErrors == 0)
	{

		if (!FormatMessage(FORMAT_MESSAGE_ALLOCATE_BUFFER | FORMAT_MESSAGE_FROM_SYSTEM | FORMAT_MESSAGE_IGNORE_INSERTS,
			NULL, GetLastError(), MAKELANGID(LANG_NEUTRAL, SUBLANG_DEFAULT),
			(LPTSTR)&lpBuffer, 0, NULL)) return;
		MessageBox(NULL, (LPCTSTR)lpBuffer, "System Error", MB_OK);
		LocalFree(lpBuffer);
	}
}
