#define OBJECTSHADER_COMPILE_VS
#define OBJECTSHADER_LAYOUT_COMMON
#define OBJECTSHADER_USE_ROTATIONAXIS
#define BLOODDAMAGE
#define OBJECTSHADER_USE_POSITION3D
#define OBJECTSHADER_USE_COLOR

#include "objectHF.hlsli"
